---
title: Hi Forex.Github.Io
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: HiForex
description: 我的交易随笔
avatar: https://at.alicdn.com/t/font_1841890_h39xgu8y92a.svg#iconfont
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: barryclark/jekyll-now
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: jekyllrb
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: 
baseurl: 
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
