---
title: Hi Forex - 我的交易随笔
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: HiForex，你好汇友
description: 我的交易随笔5
avatar: "\" style=\"width:0px;height:0px\" />\t\t\t<span class=\"iconfont\">&#xe600;</span>\t\t\t<img
  style=\"width:0px;height:0px\" src=\""
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: barryclark/jekyll-now
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: jekyllrb
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: 
baseurl: 
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
